### ISSUE TITLE
Replicate the "PaperBot" services available via IRC and Slack

### ISSUE THREAD

**Issue by tahonermann** [cplusplus/mattermost#1]
The IRC and Slack chat services previously used by some WG21 participants feature a bot service that responds to chats that contain references to papers, CWG issues, or LWG issues by replying with additional information about the mentioned items. For example:
> Carmen Chair: Discussion of [P0990R0] is starting now. [P0989R0] is up next in about 30 minutes.
> npaperbot: [[P0990R0]: [EWG] Rebuttal of Implementation Concerns for Bit Entanglement](https://wg21.link/p0990r0) (by Tony Van Eerd) (2018-04-01)
> npaperbot: [[P0989R0]: [EWG] Standardizing Extended Integers](https://wg21.link/p0989r0) (by Tony Van Eerd) (2018-04-01)

This is a useful service that would be worth replicating in Mattermost.

**Comment by tahonermann** [comment]
Source code for the Slack PaperBot service is available at https://github.com/CPPAlliance/paperbot.

**Comment by tahonermann** [comment]
Source code for the wg21.link service is available at https://github.com/cplusplus/papers; it might be useful as a reference when implementing a solution for this issue.

**Comment by tahonermann** [comment]
Source code for the implementation used during the 2022 Kona and 2023 Issaquah meetings is available at https://gitlab.ring-0.net/bueddl/isocpp-paperbot.

**Comment by tahonermann** [comment]
For reference, there are currently two bot accounts setup on the server:
- Paper Bot (@paperbot)
  - Used for running the production version of the paper bot service.
- Test Paper Bot (@testpaperbot)
  - Used for testing in-development versions of the paper bot service.

**Comment by Bueddl** [comment]
Rewrite of the bot is available in the branch in PR #2.
