### ISSUE TITLE
Paperbot: Add command to invalidate the cache

### ISSUE THREAD

**Issue by Bueddl** [cplusplus/mattermost#7]
Sometimes it is useful to refresh the paper index immediately which is why we should add a command for this (for example to account for recently published papers).

**Comment by Bueddl** [comment]
Added `updateindex` for this purpose. However this only uses the paper index at wg21.link at the moment, so there will be an additional delay until the index is updated. We will likely query the papersystem directly in the future.

**Comment by tahonermann** [comment]
Excellent, thank you for implementing this! Would it make sense to update the help command output to include this command (and perhaps `version` and `uptime` as well)? It is ok if you think users should remain blissfully unaware of these options.
